---
- hosts: localhost

  vars:
    - app_label: click-reviews.ubuntu.com
    - code_archive: "{{ build_label }}/rnr-server.tgz"

  roles:
    - role: wsgi-app
      listen_port: 8080
      python_path: "{{ application_dir }}/django-project:{{ current_code_dir }}/src"
      wsgi_application: clickreviewsproject.wsgi:application
      when: build_label != ''

    - role: nrpe-external-master
      check_name: check_http
      check_params: "-I 127.0.0.1 -p 8080 -e ' 200 OK' -s 'It works!' -u '/'"
      service_description: "Verify wsgi-example is responding."

  tasks:

    - name: Install any required packages for your app.
      apt: pkg={{ item }}
      with_items:
        - python-django=1.5.4-1ubuntu1~ctools0
        - python-tz
        - python-pip
        - python-psycopg2
      tags:
        - install
        - upgrade-charm

    - name: Copy the project configuration
      copy: src=django-project dest={{ application_dir }} owner={{ wsgi_user }} group={{ wsgi_group }}
      tags:
        - install
        - upgrade-charm
      notify:
        - Restart wsgi

    - name: Write the settings
      template:
        src: "templates/settings.py.j2"
        dest: "{{ application_dir }}/django-project/clickreviewsproject/settings.py"
        owner: "{{ wsgi_user }}"
        group: "{{ wsgi_group }}"
      tags:
        - config-changed
      notify:
        - Restart wsgi

    - name: Write the database settings
      template:
        src: "templates/database_settings.py.j2"
        dest: "{{ application_dir }}/django-project/clickreviewsproject/database_settings.py"
        owner: "{{ wsgi_user }}"
        group: "{{ wsgi_group }}"
      tags:
        - db-relation-changed
      notify:
        - Restart wsgi
      when: "'database' in current_relation"

    # XXX Normally our deployment build would ensure these are all available in the tarball.
    - name: Install any non-distro dependencies (Don't depend on pip for a real deployment!)
      pip: name={{ item.key }} version={{ item.value }}
      with_dict:
        south: 0.7.6
        django-openid-auth: 0.2
      tags:
        - install
        - upgrade-charm

    - name: sync the database
      django_manage: >
        command="syncdb --noinput"
        app_path="{{ application_dir }}/django-project"
        pythonpath="{{ code_dir }}/current/src"
      tags:
        - syncdb
