---
- hosts: localhost

  vars:
    - app_label: click-reviews.ubuntu.com

  roles:
    - role: wsgi-app
      listen_port: 8080
      python_path: "{{ application_dir }}/django-project:{{ current_code_dir }}/src"
      wsgi_application: clickreviewsproject.wsgi:application
      code_archive: "{{ build_label }}/rnr-server.tgz"
      when: build_label != ''

    - role: nrpe-external-master
      check_name: check_http
      check_params: "-I 127.0.0.1 -p 8080 -e ' 200 OK' -s 'It works!' -u '/'"
      service_description: "Verify wsgi-example is responding."

  tasks:

    - name: Install any required packages for your app.
      apt: pkg={{ item }}
      with_items:
        - python-django=1.5.4-1ubuntu1~ctools0
      tags:
        - install
        - upgrade-charm

    - name: Write any custom configuration files
      copy: src=django-project dest={{ application_dir }} owner={{ wsgi_user }} group={{ wsgi_group }}
      tags:
        - install
        - upgrade-charm
      notify:
        - Restart wsgi
