---
- hosts: localhost

  vars:
    - app_label: click-reviews.ubuntu.com

  roles:
    - role: wsgi-app
      listen_port: 8080
      wsgi_application: wsgi:app
      code_archive: "{{ build_label }}/rnr-server.tgz"
      when: build_label != ''

    - role: nrpe-external-master
      check_name: check_http
      check_params: "-I 127.0.0.1 -p 8080 -e ' 200 OK' -s 'It works!' -u '/'"
      service_description: "Verify wsgi-example is responding."

  tasks:

    # Pretend there are some package dependencies for the example wsgi app.
    - name: Install any required packages for your app.
      apt: pkg={{ item }} state=latest update_cache=yes
      with_items:
        - python-django
        - python-django-celery
      tags:
        - install
        - upgrade-charm

    - name: Write any custom configuration files
      debug: msg="You'd write any custom config files here, then notify the 'Restart wsgi' handler."
      tags:
        - config-changed
        # Also any backend relation-changed events, such as databases.
      notify:
        - Restart wsgi
