---
- name: Copy code_archive from the charm if not using code_assets_uri
  tags:
    - config-changed
  copy:
    src: "{{ charm_dir }}/files/{{ code_archive }}"
    dest: "{{ archives_dir }}/{{ code_archive }}"
    force: no
    owner: "{{ wsgi_user }}"
    group: "{{ wsgi_group }}"
    mode: 0644
  when: code_assets_uri == ""

- name: Download code tarball archive from the code assets uri
  tags:
    - config-changed
  get_url:
    url: "{{ code_assets_uri }}/{{ code_archive }}"
    dest: "{{ archives_dir }}/{{ code_archive }}"
    force: no
    owner: "{{ wsgi_user }}"
    group: "{{ wsgi_group }}"
    mode: 0644
  when: code_assets_uri != ""

- name: Check if archive is already extracted
  tags:
    - config-changed
  stat: path={{ current_code_dir }}/EXTRACTED
  register: already_extracted

- name: Extract built app sourcecode.
  tags:
    - config-changed
  unarchive:
    src: "{{ archives_dir }}/{{ code_archive }}"
    dest: "{{ current_code_dir }}"
    owner: "{{ wsgi_user }}"
    group: "{{ wsgi_group }}"
  when: already_extracted.stat.exists == False

# The following is only necessary because the unarchived code files
# won't have the correct user/group.
- name: Set user/group for application directory.
  tags:
    - config-changed
  file: path={{ code_dir }} state=directory owner={{ wsgi_user }} group={{ wsgi_group }} recurse=yes
  when: already_extracted.stat.exists == False

- name: Touch a file to ensure that we don't extract the same archive again.
  command: /usr/bin/touch {{ current_code_dir }}/EXTRACTED
  tags:
    - config-changed
  when: already_extracted.stat.exists == False
